### PR TITLE
Support rolling mode in `FileOutputReporter`

### PR DESCRIPTION
**Pull request by V1ncentzzZ**
Support rolling mode in `FileOutputReporter`.

### CODE REVIEW

**Comment by V1ncentzzZ** [comment]
Hi @hiboyang , Would you help reivew this?

**Comment by hiboyang** [comment]
> Hi @hiboyang , Would you help reivew this?

I am not in Uber anymore, @vectorijk, do you want to take a look at this PR?

**Review by vectorijk — APPROVED** [review]

**Comment by V1ncentzzZ** [comment]
Hi @vectorijk , What should i do for next？

**Comment by vectorijk** [comment]
@V1ncentzzZ Thanks for the contribution!

**Pull request merged**
